# Generated by Django 5.2 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0002_trait_remove_customuser_date_of_birth_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='preferred_traits',
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_hobbies',
            field=models.ManyToManyField(blank=True, to='love_letter.trait'),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_lifestyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
