# Generated by Django 5.2 on 2025-05-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0003_remove_preference_preferred_traits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lifestyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='love_letter.lifestyle'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferred_lifestyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='love_letter.lifestyle'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferred_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='love_letter.relationshipgoal'),
        ),
    ]
