# Generated by Django 5.2 on 2025-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0006_migrate_existing_lifestyle_and_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='love_letter.trait'),
        ),
    ]
