# Generated by Django 5.2.1 on 2025-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcebreakerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
