# Generated by Django 5.2.2 on 2025-06-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0006_icebreakerquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='content_encrypted',
        ),
    ]
