# Generated by Django 5.2.2 on 2025-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0007_rename_content_message_content_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(default='', max_length=24),
        ),
    ]
