# Generated by Django 5.2.2 on 2025-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_letter', '0008_message_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
